In [23]:
# install dependencies
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sb

In [24]:
data = pd.read_csv('HR_comma_sep (2).csv')

In [25]:
#exploring the data
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [26]:
data.tail()

satisfaction_level  last_evaluation  number_project  \
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years    sales salary  
14994                      0  support    low  
14995                      0  support    low  
14996                      0  support    low  
14997                      0  support    low  
14998                      0  support    low

In [27]:
data.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   sales                  14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [8]:
data.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
sales                    0
salary                   0
dtype: int64

In [68]:
data.duplicated().sum()


satisfaction_level  last_evaluation  number_project  \
satisfaction_level               1.000000         0.105021       -0.142970   
last_evaluation                  0.105021         1.000000        0.349333   
number_project                  -0.142970         0.349333        1.000000   
average_montly_hours            -0.020048         0.339742        0.417211   
time_spend_company              -0.100866         0.131591        0.196786   
Work_accident                    0.058697        -0.007104       -0.004741   
left                            -0.388375         0.006567        0.023787   
promotion_last_5years            0.025605        -0.008684       -0.006064   
sales                            0.003153         0.007772        0.009268   
salary                           0.011754         0.013965        0.009672   

                       average_montly_hours  time_spend_company  \
satisfaction_level                -0.020048           -0.100866   
last_evaluation                    0.339742            0.131591   
number_project                     0.417211            0.196786   
average_montly_hours               1.000000            0.127755   
time_spend_company                 0.127755            1.000000   
Work_accident                     -0.010143            0.002120   
left                               0.071287            0.144822   
promotion_last_5years             -0.003544            0.067433   
sales                              0.003913           -0.018010   
salary                             0.007082           -0.003086   

                       Work_accident      left  promotion_last_5years  \
satisfaction_level          0.058697 -0.388375               0.025605   
last_evaluation            -0.007104  0.006567              -0.008684   
number_project             -0.004741  0.023787              -0.006064   
average_montly_hours       -0.010143  0.071287              -0.003544   
time_spend_company          0.002120  0.144822               0.067433   
Work_accident               1.000000 -0.154622               0.039245   
left                       -0.154622  1.000000              -0.061788   
promotion_last_5years       0.039245 -0.061788               1.000000   
sales                       0.003425  0.032105              -0.027336   
salary                     -0.002506 -0.001294              -0.001318   

                          sales    salary  
satisfaction_level     0.003153  0.011754  
last_evaluation        0.007772  0.013965  
number_project         0.009268  0.009672  
average_montly_hours   0.003913  0.007082  
time_spend_company    -0.018010 -0.003086  
Work_accident          0.003425 -0.002506  
left                   0.032105 -0.001294  
promotion_last_5years -0.027336 -0.001318  
sales                  1.000000  0.000685  
salary                 0.000685  1.000000

In [30]:
from sklearn.preprocessing import LabelEncoder

In [34]:
encoder = LabelEncoder()

In [35]:
data['sales'] = encoder.fit_transform(data['sales'])
data['salary'] = encoder.fit_transform(data['salary'])

In [37]:
x = data.loc[:, ['satisfaction_level', 'last_evaluation', 'number_project','average_montly_hours']]

In [49]:
y = data.iloc[:, 0].values

In [41]:
x

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  
0                       157  
1                       262  
2                       272  
3                       223  
4                       159  
...                     ...  
14994                   151  
14995                   160  
14996                   143  
14997                   280  
14998                   158  

[14999 rows x 4 columns]

In [50]:
y

array([0.38, 0.8 , 0.11, ..., 0.37, 0.11, 0.37])

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
sc = StandardScaler()
x_scaled = sc.fit_transform(x)

In [54]:
x_scaled

array([[-0.93649469, -1.08727529, -1.46286291, -0.88203988],
       [ 0.75281433,  0.84070693,  0.97111292,  1.22042276],
       [-2.02247906,  0.95755433,  2.59376348,  1.4206573 ],
       ...,
       [-0.97671633, -1.08727529, -1.46286291, -1.16236823],
       [-2.02247906,  1.42494396,  1.7824382 ,  1.58084493],
       [-0.97671633, -1.14569899, -1.46286291, -0.86201642]])

In [55]:
from  sklearn.decomposition import PCA

In [56]:
pca = PCA(n_components = 4)

In [57]:
p = pca.fit_transform(x_scaled)

In [58]:
p

array([[-1.93205404,  0.90134226,  0.06095048, -0.65435958],
       [ 1.71291662, -0.76219664, -0.41242762,  0.14451983],
       [ 3.01378468,  2.1074684 ,  0.2026485 ,  0.43338255],
       ...,
       [-2.09448712,  0.94040739,  0.25783068, -0.5380438 ],
       [ 2.87709617,  1.77782775,  0.42970836, -0.41718136],
       [-1.94986532,  0.95714494,  0.01628149, -0.65671525]])

In [67]:
principalDF = pd.DataFrame(data=p, columns = ['area1', 'area2','area3', 'area4'])
finalDF = pd.concat([principalDF, data[['salary']]], axis = 1)
finalDF.head()

area1     area2     area3     area4  salary
0 -1.932054  0.901342  0.060950 -0.654360       1
1  1.712917 -0.762197 -0.412428  0.144520       2
2  3.013785  2.107468  0.202649  0.433383       2
3  1.303532 -0.479232  0.228267  0.386646       1
4 -1.938107  0.956999  0.002919 -0.665887       1